[project]
name = "beyond-strava"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "aiohttp>=3.12.15",
  "duckdb>=1.3.2",
  "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
